services:
  - type: web
    name: jogo-de-dama
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dama:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000

